# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
