# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170418_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
